### ISSUE TITLE
Taks 1 - input field & rendering of input #2

### ISSUE THREAD

**Issue by michaelnakonechny** [michaelnakonechny/capstone-project#1]
**Value Proposition**
As a webshop customer
I want to buy and customize a product
so that i can eat it exclusively

**Description**

<img width="742" alt="Bildschirmfoto 2022-09-14 um 16 36 06" src="https://user-images.githubusercontent.com/109967687/190185313-14532d5f-a653-499b-90f7-b95c51dd2dae.png">

**Acceptance Criteria**

- choose product
- customize ingredients
- put product in cart
- proceed to checkout
- enter address OR takeaway option
- choose payment
- confirm purchase

**Tasks**

- [ ] create a branch
- [ ] create a h1 with "parkbench bagels"
- [ ] create an ordered list with menu-cards
- [ ]  create an input field form for customized bagels
- [ ] write logic for rendering the menu cards
- [ ] create a bottom nav bar with icons
- [ ] create a pop up menu for the shopping cart
- [ ] create burger menu for more info

**Comment by MerleMak** [comment]
Hi Michael, 
This User Story seems way too big. Please check the wireframe for the User Story, which we discussed earlier. The Acceptance Criteria is supposed to include the possible reactions of the app to specific actions of the user. It's not  meant to list the things that the user can do, as those are way to many for one user story. 

Please also note to only include elements into your project that have functionalities. You shouldn't display buttons that don't do anything.
For the first user story you can exclude the offer of the month, the entire navigation bar, the logo and the burger menu. Try to me as minimal as possible. Maybe just build a form for select some variants of a bagel. and with every user story you add one more feature.
