### ISSUE TITLE
User Story Task #1 updated

### ISSUE THREAD

**Issue by michaelnakonechny** [michaelnakonechny/capstone-project#2]
**Value Proposition**
As a webshop customer
I want to buy and customize a product
so that i can eat it exclusively

**Description**

<img width="370" alt="Bildschirmfoto 2022-09-15 um 16 19 54" src="https://user-images.githubusercontent.com/109967687/190428272-1203dc9e-5338-4666-bbde-0c68fab6d20c.png">

**Acceptance Criteria**

- [ ] when clicking filter buttons you get ingredients based on (veggie, vegan, meat)
- [ ] when clicking on check boxes you are adding ingredients
- [ ] when clicking on submit your personalized bagel gets into the shopping cart

**Tasks**

- [ ] create next.js app, create branch
- [ ] Create h1 with "parkbench bagels"
- [ ] create h2 with "build your own bagle"
- [ ] create unordered list with checkboxes with ingredients
- [ ] create "submit" button

**Comment by MerleMak** [comment]
Hi Michael! 
It already looks  more slim, but in a conversation with Lene, she noted, that the filter options "meat" "veggie and "vegan" will include a  lot of work. In order to not work on your first user story for a full week, we recommend that your first story should include only the "Build your Bagel" functionality. Your next Userstory could be adding a filter for meat and veggie and the one after that could ass the vegan filter option. 

Also the arrows to select the ingredients could be checkboxes in the first step, als the arrows are work intensive as well. 

Referring to the tasks: 
The first point says "create-react-app", you will be working on a next-app :P
Also specify in the task which logic you will need specifically. Think about how to tackle the individual components in your app already now.
Good Luck :)

**Comment by michaelnakonechny** [comment]
@MerleMak updated :)
