### ISSUE TITLE
User Story Task #2

### ISSUE THREAD

**Issue by michaelnakonechny** [michaelnakonechny/capstone-project#3]
**Value Proposition**
As a webshop customer
I want to filter my ingredients for veggie options
so that i can avoid eating meat

**Description**

<img width="370" alt="Bildschirmfoto 2022-09-15 um 16 21 51" src="https://user-images.githubusercontent.com/109967687/190428745-ccc28201-a9b2-42ce-8d64-36fd50b25eed.png">

**Acceptance Criteria**

- [ ] when clicking filter buttons you get ingredients based on (veggie, vegan, meat)
- [ ] when clicking on submit your personalized bagel gets into the shopping cart

**Tasks**

- [ ] create three buttons which filter ingredients
- [ ] write logic for filtering components
